import { ref, computed } from "vue";
import { useRouter } from "vue-router";
import { defineStore } from "pinia";
import axios from "axios";

const skillList = [
  "컴퓨터 견적",
  "CPU 장착",
  "SSD/RAM 장착",
  "배선 작업",
  "수냉 쿨러",
  "케이스 선택",
  "전원 공급 장치 설치",
  "BIOS 설정",
  "드라이버 설치",
  "온도 관리",
  "업그레이드 팁",
  "모니터 연결",
  "전원 버튼 연결",
  "마더보드 선택",
  "고성능 게이밍 컴퓨터 조립",
  "소형 폼팩터 컴퓨터 조립",
  "사운드 카드 설치",
  "Wi-Fi 설정",
  "벤치마크 퍼포먼스 조정",
  "에러 코드 해결",
  "백업 및 복원",
  "NAS 관련 데이터 전송",
  "디스크 파티션 설정",
  "소음 감소 팁",
  "리눅스 설치 및 구성",
  "IOT 장치 연결",
  "데이터 복구",
];

export const useFiltersStore = defineStore("filters", () => {
  const filterList = ref({
    cpu: {
      manufacturer: ["인텔", "AMD"],
      intelCpuTypes: [
        "코어i9-14세대",
        "코어i7-14세대",
        "코어i5-14세대",
        "코어i3-14세대",
        "프로세서",
        "코어i9-13세대",
        "코어i7-13세대",
        "코어i5-13세대",
        "코어i3-13세대",
        "코어i9-12세대",
        "코어i7-12세대",
        "코어i5-12세대",
        "코어i3-12세대",
        "코어i9-11세대",
        "코어i7-11세대",
        "코어i5-11세대",
        "코어i9-10세대",
        "코어i7-10세대",
        "코어i5-10세대",
        "코어i3-10세대",
        "코어X-시리즈",
        "코어i9-9세대",
        "코어i7-9세대",
        "코어i5-9세대",
        "코어i3-9세대",
        "코어i7-8세대",
        "코어i5-8세대",
        "코어i3-8세대",
        "코어i7-7세대",
        "코어i5-7세대",
        "코어i3-7세대",
        "코어i7-6세대",
        "코어i5-6세대",
        "코어i3-6세대",
        "코어i7-4세대",
        "코어i5-4세대",
        "코어i3-4세대",
        "코어i7-3세대",
        "코어i5-3세대",
        "코어i3-3세대",
        "코어i7-2세대",
        "코어i5-2세대",
        "코어i3-2세대",
        "코어i7",
        "코어i5",
        "코어i3",
        "코어2쿼드",
        "코어2듀오",
        "펜티엄 골드",
        "펜티엄",
        "셀러론",
        "제온 W",
        "제온 E",
        "제온 플래티넘",
        "제온 골드",
        "제온 실버",
        "제온 브론즈",
        "제온",
      ],
      amdCpuTypes: [
        "라이젠9-5세대",
        "라이젠7-5세대",
        "라이젠5-5세대",
        "라이젠7-4세대",
        "라이젠5-4세대",
        "라이젠9-4세대",
        "라이젠9-3세대",
        "라이젠7-3세대",
        "라이젠5-3세대",
        "라이젠3-3세대",
        "라이젠 스레드리퍼 PRO",
        "라이젠 스레드리퍼",
        "라이젠9 PRO",
        "라이젠7 PRO",
        "라이젠5 PRO",
        "라이젠3 PRO",
        "애슬론 APU",
        "EPYC",
        "라이젠7-2세대",
        "라이젠5-2세대",
        "라이젠3-2세대",
        "라이젠7-1세대",
        "라이젠5-1세대",
        "라이젠3-1세대",
        "FX",
        "리치랜드-A4",
        "라노-A4",
        "페넘II-X6",
        "페넘II-X4",
        "페넘II-X3",
        "애슬론II-X4",
        "애슬론II-X3",
      ],
      socketTypes: [
        "인텔(소켓1700)",
        "인텔(소켓1200)",
        "인텔(소켓2066)",
        "AMD(소켓AM5)",
        "AMD(소켓AM4)",
        "인텔(소켓4677)",
        "인텔(소켓4189)",
        "인텔(소켓3647)",
        "인텔(소켓1151v2)",
        "인텔(소켓1151)",
        "인텔(소켓2011-V3)",
        "인텔(소켓2011)",
        "인텔(소켓1366)",
        "인텔(소켓1150)",
        "인텔(소켓1155)",
        "인텔(소켓1156)",
        "인텔(소켓775)",
        "AMD(소켓sTR5)",
        "AMD(소켓sWRX8)",
        "AMD(소켓sTRX4)",
        "AMD(소켓SP3)",
        "AMD(소켓TR4)",
        "AMD(소켓FM2)",
        "AMD(소켓FM1)",
        "AMD(소켓AM3+)",
        "AMD(소켓AM3)",
      ],
      manufacturingProcesses: [
        "5nm",
        "7nm",
        "10nm",
        "12nm",
        "14nm",
        "4nm",
        "22nm",
        "45nm",
        "32nm",
        "65nm",
      ],
      coreCounts: [
        "2코어",
        "4코어",
        "6코어",
        "8코어",
        "10코어",
        "12코어",
        "14코어",
        "16코어",
        "24코어",
        "96코어",
        "64코어",
        "40코어",
        "38코어",
        "36코어",
        "32코어",
        "28코어",
        "26코어",
        "22코어",
        "20코어",
        "18코어",
        "3코어",
      ],
      threadCounts: [
        "2스레드",
        "4스레드",
        "6스레드",
        "8스레드",
        "12스레드",
        "192스레드",
        "128스레드",
        "80스레드",
        "76스레드",
        "72스레드",
        "64스레드",
        "56스레드",
        "52스레드",
        "48스레드",
        "44스레드",
        "40스레드",
        "36스레드",
        "32스레드",
        "28스레드",
        "24스레드",
        "20스레드",
        "16스레드",
        "3스레드",
      ],
      baseClocks: [
        "4.5 ~ 4.99 GHz",
        "4.0 ~ 4.49 GHz",
        "3.5 ~ 3.99 GHz",
        "3.0 ~ 3.49 GHz",
        "2.5 ~ 2.99 GHz",
        "2.0 ~ 2.49 GHz",
        "1.5 ~ 1.99 GHz",
        "1.0 ~ 1.49 GHz",
      ],
      boostClocks: [
        "6.0GHz 이상 GHz",
        "5.0 ~ 5.99 GHz",
        "4.5 ~ 4.99 GHz",
        "4.0 ~ 4.49 GHz",
        "3.5 ~ 3.99 GHz",
        "3.0 ~ 3.49 GHz",
        "2.5 ~ 2.99 GHz",
        "2.0 미만 GHz",
      ],
      l3Caches: [
        "384MB",
        "256MB",
        "128MB",
        "96MB",
        "75MB",
        "64MB",
        "60MB",
        "57MB",
        "54MB",
        "48MB",
        "45MB",
        "42MB",
        "39MB",
        "38.5MB",
        "36MB",
        "35.75MB",
        "35MB",
        "33.75MB",
        "33MB",
        "32MB",
        "30.25MB",
        "30MB",
        "25MB",
        "24MB",
        "27.5MB",
        "24.75MB",
        "22MB",
        "20MB",
        "19.25MB",
        "18MB",
        "16.5MB",
        "16MB",
        "15MB",
        "13.75MB",
        "12MB",
        "11MB",
        "10MB",
        "9MB",
        "8.25MB",
        "8MB",
        "6MB",
        "4MB",
        "3MB",
        "2MB",
      ],
      tdps: [
        "49 미만 W",
        "50 ~ 75 W",
        "76 ~ 99 W",
        "100 W",
        "105 W",
        "115 W",
        "117 W",
        "120 W",
        "125 W",
        "130 W",
        "135 W",
        "140 W",
        "150 W",
        "155 W",
        "165 W",
        "170 W",
        "180 W",
        "185 W",
        "190 W",
        "195 W",
        "200 W",
        "202 W",
        "205 W",
        "225 W",
        "230 W",
        "235 W",
        "240 W",
        "241 W",
        "250 W",
        "270 W",
        "280 W",
        "350 W",
      ],
      pcieVersions: ["PCIe5.0", "PCIe5.0, 4.0", "PCIe4.0", "PCIe3.0"],
      maxPcieLanes: [
        "148레인",
        "128레인",
        "112레인",
        "92레인",
        "68레인",
        "64레인",
        "48레인",
        "44레인",
        "40레인",
        "28(24)레인",
        "24(20)레인",
        "20레인",
        "16+4레인",
        "20(16)레인",
        "16레인",
        "14(10)레인",
        "8레인",
      ],
      maxMemorySizes: [
        "6TB",
        "4.5TB",
        "4TB",
        "2TB",
        "1TB",
        "256GB",
        "192GB",
        "128GB",
        "64GB",
      ],
      memoryTypes: [
        "DDR5",
        "DDR5, DDR4",
        "DDR4",
        "DDR4, DDR3L",
        "DDR3",
        "DDR3, DDR2",
      ],
      memorySpeeds: [
        "5600, 3200MHz",
        "5200MHz",
        "4800MHz",
        "4800, 3200MHz",
        "3200MHz",
        "2993MHz",
        "2933MHz",
        "2667MHz",
        "2666MHz",
        "2400MHz",
        "2133MHz",
        "2000MHz",
        "1866MHz",
        "1333MHz",
        "1066MHz",
        "800MHz",
      ],
      integratedGraphics: ["내장그래픽: 탑재", "내장그래픽: 미탑재"],
      gpuModels: [
        "인텔 UHD 770",
        "인텔 UHD 750",
        "인텔 UHD 730",
        "인텔 UHD 710",
        "AMD 라데온 780M",
        "AMD 라데온 760M",
        "AMD 라데온 740M",
        "인텔 UHD 630",
        "인텔 UHD P630",
        "인텔 UHD 610",
        "인텔 HD 610",
        "인텔 HD 630",
        "인텔 HD P630",
        "인텔 HD 510",
        "인텔 HD 530",
        "인텔 HD 2000",
        "인텔 HD 2500",
        "인텔 HD 3000",
        "인텔 HD 4000",
        "인텔 HD 4400",
        "인텔 HD 4600",
        "인텔 HD",
        "AMD 라데온 그래픽",
        "AMD 라데온 그래픽 8",
        "AMD 라데온 그래픽 7",
        "AMD 라데온 그래픽 6",
        "AMD 라데온 Vega 11",
        "AMD 라데온 Vega 8",
        "AMD 라데온 Vega 3",
        "AMD HD 8470D",
        "AMD HD 6410D",
      ],
      supportedTechnologies: [
        "AMD 3D V캐시",
        "하이퍼스레딩/SMT",
        "인텔 XTU",
        "인텔 퀵싱크",
        "옵테인",
        "인텔 딥러닝부스트",
        "SenseMI",
        "StoreMI",
        "AMD Ryzen Master",
        "VR Ready 프리미엄",
        "AMD PRO",
        "AMD Ryzen AI",
      ],
      codeNames: [
        "랩터레이크-R (2023)",
        "랩터레이크 (2022)",
        "피닉스 (2024)",
        "라파엘 (2022)",
        "버미어 (2020)",
        "사파이어 래피즈(2023)",
        "엘더레이크 (2021)",
        "쿠퍼레이크 (2020)",
        "아이스레이크 (2021)",
        "로켓레이크S (2021)",
        "코멧레이크S-R (2021)",
        "코멧레이크S (2020)",
        "캐스케이드레이크 (2019)",
        "커피레이크-R (2018)",
        "커피레이크 (2017)",
        "카비레이크 (2017)",
        "스카이레이크 (2015)",
        "데빌스캐년 (2014)",
        "하스웰 리프레시 (2014)",
        "하스웰 (2013)",
        "아이비브릿지 (2012)",
        "샌디브릿지 (2011)",
        "클락데일 (2010)",
        "웨스트미어 (2010)",
        "린필드 (2008)",
        "요크필드 (2007)",
        "켄츠필드 (2006)",
        "스톰 픽 (2023)",
        "샤갈 프로 (2022)",
        "르누아르-X (2022)",
        "세잔 (2021)",
        "캐슬 픽-W (2021)",
        "밀라노 (2021)",
        "르누아르 (2020)",
        "캐슬 픽 (2019)",
        "롬(2019)",
        "마티스 (2019)",
        "피카소 (2019)",
        "콜팩스 (2018)",
        "피나클 릿지 (2018)",
        "레이븐 릿지 (2018)",
        "화이트헤븐 (2017)",
        "서밋 릿지 (2017)",
        "리치랜드 (2013)",
        "비쉐라 (2012)",
        "라노 (2011)",
        "투반 (2010)",
        "데네브 (2009)",
        "헤카 (2009)",
        "라나 (2009)",
        "프로푸스 (2009)",
        "네할렘 (2008)",
        "울프데일 (2008)",
        "콘로 (2006)",
      ],
      packageTypes: [
        "정품",
        "멀티팩(정품)",
        "병행수입 박스",
        "벌크 + 쿨러",
        "벌크",
        "해외구매",
        "중고",
      ],
      coolerTypes: [
        "인텔 기본쿨러 포함",
        "Wraith PRISM 포함",
        "Wraith Spire 포함",
        "Wraith Stealth 포함",
        "미포함",
        "Wraith Spire(LED) 포함",
        "AMD 기본쿨러 포함",
        "기본형 벌크쿨러",
      ],
    },
    coolerTuning: {
      manufacturer: [
        "맥스엘리트",
        "PCCOOLER",
        "MSI",
        "이엠텍",
        "darkFlash",
        "NZXT",
        "쿨러마스터",
        "CORSAIR",
        "에너맥스",
        "써멀테이크",
        "DEEPCOOL",
        "잘만",
        "NOCTUA",
        "ASUS",
        "마이크로닉스",
        "리안리",
        "be quiet",
        "AEROCOOL",
        "앱코",
        "1stPlayer",
        "3RSYS",
        "ACASIS",
        "ADATA",
        "AKASA",
        "ALPHACOOL",
        "ALSEYE",
        "AMD",
        "AMeCh",
        "ANIX",
        "AONE",
        "APNX",
        "ARCTIC",
        "ARX",
        "ASRock",
        "AVC",
        "AddA",
        "AiOLOS",
        "Antec",
        "BARROW",
        "BLACKNOISE",
        "BRAVOTEC",
        "BYKSKI",
        "Bi-Sonic",
        "COLORFUL",
        "COOLCOM",
        "COOLERTEC",
        "COOLMAI",
        "COOLMARKER",
        "COOLMOON",
        "COUGAR",
        "CRAFT",
        "CRYORIG",
        "CYNEX",
        "CeramTec",
        "CoolAge",
        "CoolJag",
        "Coollaboratory",
        "DAVEN",
        "DELL",
        "DIGIX",
        "DYNATRON",
        "EVERCOOL",
        "EVERFLOW",
        "EVGA",
        "ElectroCookie",
        "EnerwayTech",
        "FOXCONN",
        "FREEZEMOD",
        "FSP",
        "Fonsoning",
        "Fractal Design",
        "Frostwind",
        "G.SKILL",
        "GAMDIAS",
        "GELID",
        "GEO메트릭퓨처",
        "GIGABYTE",
        "GIGAZONE",
        "GLOBEFAN",
        "GeIL",
        "GreatWall",
        "HDTOP",
        "HIKSEMI",
        "HYTE",
        "Halnziye",
        "ICE SHIELD",
        "ICEGIANT",
        "ID-COOLING",
        "IN WIN",
        "Iceberg Thermal",
        "JAMICON",
        "JEYI",
        "JIUSHARK",
        "JONSBO",
        "JunPus",
        "KRAFT KOREA",
        "Kingpin cooling",
        "LAMPTRON",
        "LEADCOOL",
        "Lesozoh",
        "MAGICOOL",
        "MAXTEK",
        "MOCOOLING",
        "MONTECH",
        "MySSD",
        "NCTOP",
        "NETmate",
        "NMB",
        "NOFAN",
        "Nidec",
        "ORBIS",
        "ORICO",
        "ORITEK",
        "OTAO",
        "PB이노베이션",
        "PNC PARTNER",
        "PNY",
        "POWERYEAR",
        "PROLIMATECH",
        "PentaWave",
        "Phanteks",
        "Power Logic",
        "QIHUIDA",
        "RAIDMAX",
        "RAIJINTEK",
        "REEVEN",
        "REX COOL",
        "RISUN",
        "RUNDA",
        "Razer",
        "SAMA",
        "SANYO DENKI",
        "SAPPHIRE",
        "SCYTHE",
        "SHARKOON",
        "SK하이닉스",
        "SNOWMAN",
        "STstore",
        "SUNON",
        "SWCHEM",
        "Segotep",
        "Shenzhen Newtech",
        "SilenX",
        "SilverStone",
        "Supermicro",
        "T&T",
        "TITAN",
        "TYAN",
        "TaiSol",
        "Thermal Grizzly",
        "Thermalright",
        "XASTRA",
        "XIGMATEK",
        "Xingdong",
        "ZOTAC",
        "Zezzio",
        "Zizzy",
        "agecooler",
        "archon",
        "coolwhist",
        "delifen",
        "ebmpapst",
        "iHTP",
        "topower",
        "upHere",
        "가넷씨앤아이",
        "갤럭시",
        "건평정보통신",
        "다산코퍼레이션",
        "대양케이스",
        "대원TMT",
        "델타",
        "디지탈그리고나",
        "디직스",
        "라이트컴",
        "라인업시스템",
        "리버네트워크",
        "리뷰안",
        "마하링크",
        "명인일렉트로닉스",
        "몬스타",
        "바이퍼테크",
        "발키리",
        "배럴즈",
        "블루트레이더스",
        "비에스컴퓨터",
        "비콘즈",
        "산와서플라이",
        "삼척전자",
        "샤칸",
        "세컨드찬스",
        "시소닉",
        "시스기어",
        "싸이오닉",
        "써모랩",
        "아이구주",
        "아이티젠",
        "야인컴퓨터",
        "얼티메이크",
        "에너지옵티머스",
        "엔에프씨앤씨",
        "엠디디지탈",
        "엠비에프",
        "엠스톤글로벌",
        "오메이",
        "오존컴퍼니",
        "와이피씨앤씨",
        "우앤이",
        "유지테크",
        "유커머스",
        "이메이크",
        "인텔",
        "장우컴퍼니",
        "제이맥스씨앤씨",
        "제이엠지글로벌",
        "젬스톤",
        "조이쿨",
        "컨트롤프릭",
        "컴스마트",
        "컴이지",
        "컴튜",
        "케이엘시스템",
        "투포인츠",
        "티엔아이",
        "티테크놀로지",
        "포게임",
        "프로테크닉",
        "프리플로우",
        "피닉스CNS",
        "픽스콤",
        "하이케이넷",
        "확인중",
      ],
      productType: [
        "CPU 쿨러",
        "써멀컴파운드(그리스)",
        "시스템 쿨러",
        "M.2 SSD 쿨러",
        "VGA 지지대",
        "VGA 쿨러",
        "방열판",
        "RAM 쿨러",
        "HDD 쿨러",
        "팬컨트롤러",
        "써멀패드",
        "조명기기",
        "가이드",
        "팬 부속품",
        "수랭 부속품",
        "튜닝 용품",
      ],
      coolingType: ["공랭", "수랭"],
      warranty: [
        "6년+누수보상",
        "5년+누수보상",
        "3년+누수보상",
        "팬1년+누수보상",
        "5년",
        "10년",
        "6년",
        "5년",
        "3년",
        "2년",
        "1년",
        "6개월",
        "3개월",
        "1개월",
      ],
      intelSocket: [
        "LGA1700",
        "LGA1200",
        "LGA115x",
        "LGA2011-V3",
        "LGA2066",
        "LGA1851",
        "LGA4677",
        "LGA4189-4/5(소켓P4/P5)",
        "LGA3647",
        "LGA2011",
        "LGA1366",
        "LGA775",
        "LGA771",
        "소켓478",
        "소켓370",
      ],
      amdSocket: [
        "AM5",
        "AM4",
        "sWRX8",
        "sTRX4",
        "TR4",
        "FMx/AM2,3",
        "AM1",
        "TR5(sTRX5/sWRX9)",
        "SP6",
        "SP5",
        "SP3",
        "소켓939",
        "소켓754",
        "소켓940",
        "소켓A",
        "소켓F",
      ],
      height: [
        "165~ mm",
        "150~164 mm",
        "125~149 mm",
        "100~124 mm",
        "75~99 mm",
        "50~74 mm",
        "19~49 mm",
        "16~18 mm",
        "13~15 mm",
        "10~12 mm",
        "7~9 mm",
        "4~6 mm",
        "~3 mm",
      ],
      radiator: ["4열", "3열", "2열", "1열", "3x3열"],
      fanSize: [
        "140mm",
        "120mm",
        "95mm",
        "92mm",
        "80mm",
        "150mm 이상",
        "136mm",
        "135mm",
        "130mm",
        "110mm",
        "100mm",
        "97mm",
        "96mm",
        "90mm",
        "85mm",
        "78mm",
        "75mm",
        "70mm",
        "65mm",
        "60mm",
        "50mm",
        "45mm",
        "40mm",
        "35mm",
        "30mm 이하",
      ],
      bearingType: [
        "FDB(유체)",
        "Rifle(유체)",
        "Hydraulic(유체)",
        "Hydro(유체)",
        "Hypro(유체)",
        "S-FDB V2(유체)",
        "S-FDB(유체)",
        "EBR(유체)",
        "LDB(유체)",
        "EL(유체)",
        "Superflo(유체)",
        "SPFDB(유체)",
        "SPFDB2(유체+마그네틱)",
        "FCB(유체)",
        "HDB(유체)",
        "Hydraumatic(유체)",
        "Hydromatic(유체)",
        "Axially grooved(유체)",
        "유체",
        "Long Life Sleeve",
        "HPLN(슬리브)",
        "UFB(슬리브)",
        "슬리브",
        "2볼",
        "볼",
        "NBRX(슬리브+마그네틱)",
        "SSO2(유체+마그네틱)",
        "SSO(유체+마그네틱)",
        "MHDB(유체+마그네틱)",
        "MFDB(유체+마그네틱)",
        "Magnetic Levitation",
        "Magnetic Dome",
        "NANO-SLI2(Magnetic)",
        "Twister(마그네틱볼)",
        "TNB(공압)",
        "NANO",
      ],
      maxFanSpeed: [
        "3001 RPM 이상",
        "3000 RPM 이하",
        "2500 RPM 이하",
        "2000 RPM 이하",
      ],
      maxAirFlow: [
        "90 CFM 이상",
        "80 ~ 89 CFM",
        "70 ~ 79 CFM",
        "60 ~ 69 CFM",
        "50 ~ 59 CFM",
        "40 ~ 49 CFM",
        "30 ~ 39 CFM",
        "30 CFM 미만",
      ],
      minFanNoise: ["21~ dBA", "16~20dBA", "11~15dBA", "~10dBA"],
      maxFanNoise: [
        "36~ dBA",
        "31~35 dBA",
        "26~30 dBA",
        "21~25 dBA",
        "~20 dBA",
      ],
      ledSystem: [
        "AURA SYNC",
        "MYSTIC LIGHT",
        "RGB FUSION",
        "POLYCHROME",
        "RGB LED",
        "CHROMA",
        "VIVID",
        "BIOSTAR SYNC",
        "제조사 소프트웨어",
      ],
      additionalFeatures: [
        "LED 라이트",
        "PWM 지원",
        "RGB 컨트롤러",
        "팬허브(컨트롤러)",
        "리모콘 지원",
        "펌프속도조절",
        "워터블록/로고 회전",
        "LCD인디게이터",
        "데이지체인",
        "제로팬(0-dB기술)",
        "수랭 커스텀",
        "속도조절스위치",
        "라디에이터 양면팬 지원",
        "자석 고정형",
      ],
      thermalType: [
        "주사기형",
        "튜브형",
        "브러시형",
        "용기형",
        "1회용파우치",
        "도포후출고",
        "테이프 부착",
      ],
    },
    motherboard: {
      manufacturer: [
        "MSI",
        "ASUS",
        "ASRock",
        "GIGABYTE",
        "ECS",
        "NZXT",
        "BIOSTAR",
        "AFOX",
        "ASRock Rack",
        "ATUM",
        "Arduino",
        "COLORFUL",
        "FOXCONN",
        "GIGAIPC",
        "KHADAS",
        "LattePanda",
        "MAXSUN",
        "NVIDIA",
        "PEGATRON",
        "Raspberry Pi",
        "Retroflag",
        "Supermicro",
        "마이크로틱",
        "삼성전자",
        "아이노비아",
        "액슬",
        "에너지옵티머스",
        "코코아팹",
        "쿨러마스터",
        "확인중",
      ],
      productType: ["인텔 CPU용", "AMD CPU용", "임베디드", "주변기기"],
      cpuSocket: [
        "인텔(소켓1700)",
        "인텔(소켓1200)",
        "AMD(소켓AM5)",
        "AMD(소켓AM4)",
        "AMD(소켓sTRX4)",
        "AMD(소켓sTR5)",
        "AMD(소켓sWRX8)",
        "AMD(소켓TR4)",
        "AMD(소켓SP5)",
        "AMD(소켓SP3)",
        "인텔(소켓4677)",
        "인텔(소켓4189)",
        "인텔(소켓1151v2)",
        "인텔(소켓1151)",
        "인텔(소켓2066)",
        "인텔(소켓3647)",
        "인텔(소켓1150)",
        "인텔(소켓1155)",
        "인텔(소켓1156)",
        "인텔(소켓775)",
        "인텔(소켓1170)",
        "인텔(CPU내장)",
        "AMD(소켓AM2+)",
        "ARM(CPU내장)",
        "ATMEL(CPU내장)",
        "Rockchip(CPU내장)",
        "기타",
        "VIA(CPU내장)",
      ],
      chipset: [
        "인텔 Z790",
        "인텔 B760",
        "인텔 H610",
        "AMD B650",
        "AMD A620",
        "인텔 Z690",
        "인텔 B660",
        "AMD X670",
        "AMD B550",
        "AMD A520",
        "AMD X670E",
        "AMD B650E",
        "AMD WRX90",
        "AMD TRX50",
        "AMD WRX80",
        "AMD TRX40",
        "AMD X570",
        "AMD X470",
        "AMD B450",
        "AMD A320",
        "AMD B350",
        "AMD X399",
        "인텔 W790",
        "인텔 H770",
        "인텔 Q670E",
        "인텔 H670",
        "인텔 Z590",
        "인텔 H570",
        "인텔 B560",
        "인텔 H510",
        "인텔 Z490",
        "인텔 H470",
        "인텔 B460",
        "인텔 H410",
        "인텔 Z390",
        "인텔 H370",
        "인텔 B365",
        "인텔 B360",
        "인텔 H310",
        "인텔 Z370",
        "인텔 B250",
        "인텔 H270",
        "인텔 Z270",
        "인텔 X299",
        "인텔 Z170",
        "인텔 H170",
        "인텔 B150",
        "인텔 H110",
        "인텔 N100",
        "인텔 H97",
        "인텔 H81",
        "인텔 Q87",
        "인텔 B85",
        "인텔 H87",
        "인텔 Z87",
        "인텔 H77",
        "인텔 B75",
        "인텔 H67",
        "인텔 H61",
        "인텔 H67 (B3)",
        "인텔 H55",
        "인텔 P55",
        "인텔 G41",
        "인텔 Q35",
        "인텔 G31",
        "인텔 C741",
        "인텔 C621",
        "인텔 C621A",
        "인텔 C242",
        "인텔 C246",
        "인텔 C422",
        "인텔 C256",
        "인텔 C252",
        "인텔 C224",
        "인텔 셀러론 J4025",
        "인텔 셀러론 J4005",
        "인텔 셀러론 J1900",
        "인텔 셀러론 N4020",
        "AMD 780G",
        "인텔 W680",
        "기타",
      ],
      formFactor: [
        "ATX (30.5x24.4cm)",
        "M-ATX (24.4x24.4cm)",
        "M-iTX (17.0x17.0cm)",
        "E-ATX (30.5x33.0cm)",
        "ATX (후면커넥터)",
        "M-ATX (후면커넥터)",
        "EEB (30.5x33.0cm)",
        "기타",
      ],
      powerPhase: [
        "41~45페이즈",
        "36~40페이즈",
        "26~30페이즈",
        "21~25페이즈",
        "19~20페이즈",
        "17~18페이즈",
        "15~16페이즈",
        "13~14페이즈",
        "11~12페이즈",
        "10페이즈",
        "9페이즈",
        "8페이즈",
        "7페이즈",
        "6페이즈",
        "5페이즈",
        "4페이즈",
        "3페이즈",
        "2페이즈",
      ],
      vcoreOutput: [
        "2501~ A",
        "2001~2500 A",
        "1501~2000 A",
        "1001~1500 A",
        "501~1000 A",
        "~500 A",
      ],
      memoryType: [
        "DDR5",
        "LPDDR5",
        "DDR4",
        "LPDDR4",
        "DDR3",
        "DDR3L",
        "DDR2",
        "DDR4 노트북용",
        "DDR3 노트북용",
      ],
      memorySpeed: [
        "8400MHz (PC5-67200)",
        "8333MHz (PC5-66600)",
        "8266MHz (PC5-66128)",
        "8000MHz (PC5-64000)",
        "7800MHz (PC5-62400)",
        "7600MHz (PC5-60800)",
        "7200MHz (PC5-57600)",
        "7000MHz (PC5-56000)",
        "6800MHz (PC5-54400)",
        "6666MHz (PC5-53300)",
        "6600MHz (PC5-52800)",
        "6400MHz (PC5-51200)",
        "6200MHz (PC5-49600)",
        "6000MHz (PC5-48000)",
        "5600MHz (PC5-44800)",
        "5200MHz (PC5-41600)",
        "4800MHz (PC5-38400)",
        "4400MHz (PC5-35200)",
        "6000MHz (PC4-48000)",
        "5600MHz (PC4-44800)",
        "5333MHz (PC4-42600)",
        "5300MHz (PC4-42400)",
        "5200MHz (PC4-41600)",
        "5133MHz (PC4-41000)",
        "5100MHz (PC4-40800)",
        "5000MHz (PC4-40000)",
        "4933MHz (PC4-39400)",
        "4866MHz (PC4-38900)",
        "4800MHz (PC4-38400)",
        "4733MHz (PC4-37800)",
        "4666MHz (PC4-37300)",
        "4600MHz (PC4-36800)",
        "4533MHz (PC4-36300)",
        "4400MHz (PC4-35200)",
        "4266MHz (PC4-34100)",
        "4133MHz (PC4-33000)",
        "4066MHz (PC4-32500)",
        "3600MHz (PC4-28800)",
        "3533MHz (PC4-28200)",
        "3466MHz (PC4-27700)",
        "3300MHz (PC4-26400)",
        "3200MHz (PC4-25600)",
        "3000MHz (PC4-24000)",
        "2933MHz (PC4-23400)",
        "2666MHz (PC4-21300)",
        "2400MHz (PC4-19200)",
        "2133MHz (PC4-17000)",
        "3200MHz (PC3-25600)",
        "2800MHz (PC3-22400)",
        "2400MHz (PC3-19200)",
        "2200MHz (PC3-17600)",
        "1866MHz (PC3-14900)",
        "1600MHz (PC3-12800)",
        "1333MHz (PC3-10600)",
        "1066MHz (PC3-8500)",
        "1066MHz (PC2-8500)",
        "800MHz (PC2-6400)",
        "533MHz (PC2-4200)",
      ],
      memorySlots: ["5개 이상", "4개", "2개", "1개"],
      memoryCapacity: [
        "최대 4TB",
        "최대 3TB",
        "최대 2TB",
        "최대 1TB",
        "최대 768GB",
        "최대 256GB",
        "최대 192GB",
        "최대 128GB",
        "최대 96GB",
        "최대 64GB",
        "최대 32GB",
        "최대 16GB",
        "최대 8GB",
        "최대 4GB",
        "32GB 내장",
        "8GB 내장",
        "4GB 내장",
        "2GB 내장",
        "1GB 내장",
        "512MB 내장",
        "256MB 내장",
      ],
      vgaConnection: [
        "PCIe5.0 x16",
        "PCIe4.0 x16",
        "PCIe3.0 x16",
        "PCIe x16",
        "PCIe 호환",
      ],
      pcieVersion: ["PCIe5.0", "PCIe4.0", "PCIe3.0", "PCIe", "PCI"],
      sata: ["10개 이상", "8개", "7개", "6개", "4개", "3개", "2개", "1개"],
      m2: ["6개 이상", "5개", "4개", "3개", "2개", "1개"],
      graphicOutput: ["HDMI", "DP", "DVI", "D-SUB", "Type-C"],
      rearPorts: [
        "USB3.x 20Gbps",
        "USB3.x 10Gbps",
        "USB3.x 5Gbps",
        "썬더볼트4",
        "썬더볼트3",
        "USB4 40Gbps",
        "USB 2.0",
        "RJ-45",
        "S/PDIF",
        "오디오잭",
        "PS/2",
        "e-SATA",
        "시리얼포트",
        "패러럴포트",
        "BIOS 플래시백",
        "클리어CMOS",
      ],
      rearUsb3_20Gbps: ["후면 1개", "후면 2개"],
      rearUsb2_0: [
        "후면 1개",
        "후면 2개",
        "후면 3개",
        "후면 4개",
        "후면 5개",
        "후면 6개",
        "후면 8개",
      ],
      wiredLanChipset: [
        "Realtek",
        "Killer",
        "Intel",
        "Aquantia",
        "Marvell",
        "Broadcom",
      ],
      wirelessLanType: ["무선랜(Wi-Fi)", "블루투스", "M.2 Key-E(모듈별매)"],
      audioChipset: ["SupremeFX", "Realtek", "VIA", "ESS"],
      ledSystem: ["AURA SYNC", "MYSTIC LIGHT", "RGB FUSION", "POLYCHROME"],
    },
    memory: {
      manufacturer: [
        "삼성전자",
        "마이크론",
        "G.SKILL",
        "TeamGroup",
        "이메이션",
        "SK하이닉스",
        "ESSENCORE",
        "GeIL",
        "OCP",
        "CORSAIR",
        "ACPI",
        "ADATA",
        "AFOX",
        "ANACOMDA",
        "AVEXIR",
        "Antec",
        "Apacer",
        "ArchMemory",
        "CYNEX",
        "Dreamware",
        "EKMEMORY",
        "FINEMIND",
        "GIGABYTE",
        "GLOWAY",
        "GSM",
        "SHIKSEMI",
        "HIKVISION",
        "HP",
        "KINGMAX",
        "LANSON",
        "NEMIX RAM",
        "OLOy",
        "OWC",
        "PATRIOT",
        "PNY",
        "Ramaxel",
        "SOUTH BRIDGE",
        "TIMETEC",
        "Terabyte",
        "V-Color",
        "ZADAK",
        "brexy",
        "갤럭시",
        "마이크로",
        "실리콘파워",
        "써멀테이크",
        "아이티젠",
        "앱코",
        "에이서",
        "오존컴퍼니",
        "컴이지",
        "킹스톤",
        "타무즈",
        "트랜센드",
        "확인중",
      ],
      deviceType: ["데스크탑용", "노트북용", "서버용"],
      productTypes: ["DDR5", "DDR4", "DDR3", "DDR2", "DDR"],
      memoryCapacity: [
        "64GB",
        "32GB",
        "16GB",
        "8GB",
        "4GB",
        "256GB",
        "192GB",
        "128GB",
        "96GB",
        "48GB",
        "2GB",
        "1GB",
        "512MB",
        "256MB",
      ],
      operatingClock: [
        "8200MHz (PC5-65600)",
        "8000MHz (PC5-64000)",
        "7800MHz (PC5-62400)",
        "7600MHz (PC5-60800)",
        "7400MHz (PC5-59200)",
        "7200MHz (PC5-57600)",
        "7000MHz (PC5-56000)",
        "6800MHz (PC5-54400)",
        "6600MHz (PC5-52800)",
        "6400MHz (PC5-51200)",
        "6200MHz (PC5-49600)",
        "6000MHz (PC5-48000)",
        "5600MHz (PC5-44800)",
        "5200MHz (PC5-41600)",
        "4800MHz (PC5-38400)",
        "4800MHz (PC4-38400)",
        "4600MHz (PC4-36800)",
        "4500MHz (PC4-36000)",
        "4400MHz (PC4-35200)",
        "4300MHz (PC4-34400)",
        "4266MHz (PC4-34100)",
        "4133MHz (PC4-33000)",
        "4000MHz (PC4-32000)",
        "3866MHz (PC4-30900)",
        "3800MHz (PC4-30400)",
        "3600MHz (PC4-28800)",
        "3466MHz (PC4-27700)",
        "3400MHz (PC4-27200)",
        "3200MHz (PC4-25600)",
        "3000MHz (PC4-24000)",
        "2933MHz (PC4-23400)",
        "2666MHz (PC4-21300)",
        "2400MHz (PC4-19200)",
        "2133MHz (PC4-17000)",
        "2800MHz (PC3-22400)",
        "2666MHz (PC3-21300)",
        "2400MHz (PC3-19200)",
        "1866MHz (PC3-14900)",
        "1600MHz (PC3-12800)",
        "1333MHz (PC3-10600)",
        "1066MHz (PC3-8500)",
        "1250MHz (PC2-10000) 이하",
      ],
      ramTiming: [
        "CL14",
        "CL15",
        "CL16",
        "CL17",
        "CL18",
        "CL6",
        "CL7",
        "CL9",
        "CL10",
        "CL11",
        "CL12",
        "CL19",
        "CL20",
        "CL22",
        "CL30",
        "CL32",
        "CL34",
        "CL36",
        "CL38",
        "CL40",
        "CL42",
        "CL46",
        "CL48",
        "CL52",
      ],
      operatingVoltage: [
        "1.10V",
        "1.20V",
        "1.25V",
        "1.35V",
        "1.50V",
        "1.65V",
        "1.30V",
        "1.40V",
        "1.45V",
        "1.55V",
        "1.80V",
      ],
      numberOfModules: ["1개", "2개", "4개", "8개"],
      features: [
        "LED 라이트",
        "XMP",
        "XMP3.0",
        "EXPO",
        "온다이ECC",
        "ECC",
        "REG",
        "온도센서",
      ],
      heatSink: ["방열판", "미포함"],
      heatSinkColor: [
        "블랙",
        "화이트",
        "실버/그레이",
        "골드",
        "레드",
        "오렌지",
        "옐로우",
        "그린",
        "블루",
        "핑크",
      ],
      ledColor: ["RGB", "레드", "블루", "화이트"],
      ledSystem: [
        "AURA SYNC",
        "MYSTIC LIGHT",
        "RGB FUSION",
        "POLYCHROME",
        "RGB SYNC",
        "CORSAIR iCUE",
        "RAZER CHROMA",
        "TT RGB PLUS",
        "G.SKILL Lighting",
        "T-FORCE BLITZ",
        "XPG RGB",
      ],
    },
    gpu: {
      manufacturer: [
        "MSI",
        "이엠텍",
        "ASUS",
        "GAINWARD",
        "COLORFUL",
        "ZOTAC",
        "갤럭시",
        "GIGABYTE",
        "SAPPHIRE",
        "PALIT",
        "ADT Link",
        "AFOX",
        "AKiTiO",
        "AMD",
        "APPLE",
        "ARKTEK",
        "ASL",
        "ASRock",
        "ATUM",
        "BIOSTAR",
        "EVGA",
        "FORSA",
        "FuriosaAI",
        "HP",
        "INNO3D",
        "KEDA",
        "MANLI",
        "MAXSUN",
        "NETSTOR",
        "NVIDIA",
        "OCPC",
        "ONE-NETBOOK",
        "PNY",
        "PowerColor",
        "Razer",
        "SPARKLE",
        "STCOM",
        "Sonnet",
        "TAGER",
        "TUL",
        "XFX",
        "리드텍",
        "매트록스",
        "액슬",
        "엠탑코리아",
        "이도디스플레이",
        "인텔",
        "확인중",
      ],
      chipsetManufacturer: [
        "NVIDIA",
        "AMD(ATi)",
        "Intel",
        "Matrox",
        "FuriosaAI",
      ],
      productSeries: [
        "지포스 RTX 40",
        "지포스 RTX 30",
        "지포스 RTX 20",
        "지포스 16",
        "라데온 RX 7000",
        "라데온 RX 6000",
        "TITAN",
        "지포스 10",
        "지포스 900",
        "지포스 700",
        "지포스 600",
        "지포스 200",
        "RTX",
        "RTX A",
        "테슬라",
        "쿼드로",
        "NVS",
        "라데온 PRO",
        "라데온 RX 500",
        "라데온 RX 400",
        "Arc A",
        "매트록스 M",
        "지포스 GTS400",
        "지포스 GTS200",
        "워보이",
      ],
      gpuManufacturingProcess: [
        "4 nm",
        "8 nm",
        "12 nm",
        "14 nm",
        "16 nm",
        "28 nm",
        "40 nm",
        "5 nm",
        "6 nm",
        "7 nm",
        "55 nm",
      ],
      nvidiaChipset: [
        "RTX 4090",
        "RTX 4080 SUPER",
        "RTX 4070 Ti SUPER",
        "RTX 4070 SUPER",
        "RTX 4070",
        "RTX 4060 Ti",
        "RTX 4060",
        "RTX 4080",
        "RTX 4070 Ti",
        "RTX 3090",
        "RTX 3080 Ti",
        "RTX 3080",
        "RTX 3070 Ti",
        "RTX 3070",
        "RTX 3060 Ti",
        "RTX 3060",
        "RTX 3050",
        "TITAN V",
        "RTX 2080 Ti",
        "RTX 2080 SUPER",
        "RTX 2080",
        "RTX 2070 SUPER",
        "RTX 2070",
        "RTX 2060 SUPER",
        "RTX 2060",
        "GTX 1660 Ti",
        "GTX 1660 SUPER",
        "GTX 1660",
        "GTX 1650 SUPER",
        "GTX 1650",
        "GTX 1630",
        "GT1030",
        "GT730",
        "GT720",
        "GT710",
        "GTX1080 Ti",
        "GTX1080",
        "GTX1070 Ti",
        "GTX1070",
        "GTX1060",
        "GTX1050 Ti",
        "GTX1050",
        "T1000",
        "T400",
        "H100",
        "L40S",
        "L4A",
        "40A",
        "30A",
        "10A",
        "A2",
        "RTX 6000 Ada",
        "RTX 5000 Ada",
        "RTX 4500 Ada",
        "RTX 4000 Ada",
        "RTX 2000 Ada",
        "RTX A6000",
        "RTX A5500",
        "RTX A5000",
        "RTX A4500",
        "RTX A4000",
        "RTX A2000",
        "GTX960",
        "GTX760",
        "GTX750 Ti",
        "GTX750",
        "GTX650",
        "GTX650 Ti",
        "GTX660 Ti",
        "P620",
        "G210",
        "Tesla V100",
        "Tesla A100",
        "P4000",
        "P2000",
        "쿼드로",
        "GT610",
        "GT620",
        "GT630",
        "지포스 GTS450",
        "지포스 GTS250",
        "GTX970",
        "GTX660",
        "RTX 6000",
        "RTX 4000",
      ],
      amdChipset: [
        "RX 7900 XTX",
        "RX 7800 XT",
        "RX 7600",
        "RX 6600",
        "RX 580 2048SP",
        "RX 7900 XT",
        "RX 7900 GRE",
        "RX 7700 XT",
        "RX 7600 XT",
        "RX 6900 XT",
        "RX 6800 XT",
        "RX 6800",
        "RX 6750 XT",
        "RX 6700 XT",
        "RX 6700",
        "RX 6650 XT",
        "RX 6600 XT",
        "RX 6500 XT",
        "RX 6400",
        "W7900",
        "RX 580",
        "RX 570",
        "W7800",
        "RX 560",
        "RX 550",
        "RX 480",
        "W7700",
        "RX 470",
        "W7600",
        "W7500",
        "W6800X",
        "W6800",
        "W6600",
        "W5700",
        "W5500",
        "WX3200",
        "WX3100",
      ],
      intelChipset: [
        "ARC A770",
        "ARC A750",
        "ARC A580",
        "ARC A380",
        "ARC A310",
      ],
      baseClock: [
        "2600~2799 MHz",
        "2400~2599 MHz",
        "2200~2399 MHz",
        "2000~2199 MHz",
        "1900~1999 MHz",
        "1800~1899 MHz",
        "1700~1799 MHz",
        "1600~1699 MHz",
        "1500~1599 MHz",
        "1400~1499 MHz",
        "1300~1399 MHz",
        "1200~1299 MHz",
        "1100~1199 MHz",
        "1000~1099 MHz",
        "900~999 MHz",
        "800~899 MHz",
        "700~799 MHz",
        "600~699 MHz",
        "500~599 MHz",
      ],
      boostClock: [
        "2800~2999 MHz",
        "2600~2799 MHz",
        "2400~2599 MHz",
        "2200~2399 MHz",
        "2000~2199 MHz",
        "1900~1999 MHz",
        "1800~1899 MHz",
        "1700~1799 MHz",
        "1600~1699 MHz",
        "1500~1599 MHz",
        "1400~1499 MHz",
        "1300~1399 MHz",
        "1200~1299 MHz",
        "1100~1199 MHz",
        "1000~1099 MHz",
        "900~999 MHz",
        "700~799 MHz",
      ],
      streamProcessors: [
        "18176 개",
        "16896 개",
        "16384 개",
        "12800 개",
        "10752 개",
        "10496 개",
        "10240 개",
        "9728 개",
        "8960 개",
        "8704 개",
        "8448 개",
        "8192 개",
        "7680 개",
        "7168 개",
        "6912 개",
        "6144 개",
        "5888 개",
        "5376 개",
        "5120 개",
        "4864 개",
        "4608 개",
        "4480 개",
        "4352 개",
        "4096 개",
        "3840 개",
        "3584 개",
        "3574 개",
        "3456 개",
        "3328 개",
        "3072 개",
        "2944 개",
        "2816 개",
        "2560 개",
        "2432 개",
        "2304 개",
        "2176 개",
        "1920 개",
        "2048 개",
        "1792 개",
        "1664 개",
        "1536 개",
        "1440 개",
        "1408 개",
        "1344 개",
        "1280 개",
        "1152 개",
        "1024 개",
        "960 개",
        "896 개",
        "768 개",
        "640 개",
        "512 개",
        "384 개",
        "192 개",
        "128 개",
        "~100 개",
      ],
      interface: [
        "PCIe4.0x16",
        "PCIe4.0x16(at x8)",
        "PCIe4.0x16(at x4)",
        "PCIe4.0x8",
        "PCIe4.0",
        "PCIe5.0",
        "PCIe3.0x16",
        "PCIe3.0x16(at x8)",
        "PCIe3.0x16(at x4)",
        "PCIe2.0x16",
        "PCIe2.0x8",
        "PCIe x16",
        "기타",
      ],
      memoryType: [
        "GDDR6X(DDR6X)",
        "GDDR6(DDR6)",
        "GDDR5X(DDR5X)",
        "GDDR5(DDR5)",
        "GDDR6 ECC",
        "GDDR3(DDR3)",
        "GDDR2(DDR2)",
        "LPDDR4X(DDR4X)",
        "SDDR3(DDR3)",
        "DDR4",
        "HBM3",
        "HBM2",
      ],
      memoryCapacity: [
        "24GB",
        "16GB",
        "12GB",
        "8GB",
        "6GB",
        "94GB",
        "80GB",
        "48GB",
        "32GB",
        "20GB",
        "11GB",
        "10GB",
        "5GB",
        "4GB",
        "3GB",
        "2GB",
        "1GB",
        "1GB 미만",
      ],
      memoryBus: [
        "6144-bit",
        "4096-bit",
        "3072-bit",
        "384-bit",
        "352-bit",
        "320-bit",
        "256-bit",
        "192-bit",
        "160-bit",
        "128-bit",
        "96-bit",
        "64-bit 이하",
      ],
      outputPort: [
        "HDMI2.1",
        "HDMI2.0",
        "HDMI",
        "DP2.1",
        "DP2.0",
        "DP1.4",
        "DP",
        "mini DP2.1",
        "mini DP1.4",
        "mini DP",
        "DVI(듀얼링크)",
        "DVI",
        "D-SUB",
        "USB Type-C",
        "썬더볼트3",
        "USB3.x 5Gbps",
        "기가비트LAN",
      ],
      dvi: ["1개"],
      hdmi: ["4개", "3개", "2개", "1개", "HDMI젠더"],
      displayPort: ["6개", "4개", "3개", "2개", "1개"],
      monitorSupport: [
        "최대 모니터 5개 이상",
        "최대 모니터 4개",
        "최대 모니터 3개",
        "최대 모니터 2개",
      ],
      supportFeatures: [
        "제로팬(0-dB기술)",
        "멀티VGA 지원",
        "12K 지원",
        "8K 지원",
        "4K 지원",
        "HDR 지원",
        "HDCP 2.3",
        "HDCP 지원",
      ],
      powerConsumption: [
        "300W 이상",
        "250~299W",
        "200~249W",
        "150~199W",
        "100~149W",
        "99W 미만",
      ],
      recommendedPower: [
        "정격파워 300W 이상",
        "정격파워 350W 이상",
        "정격파워 400W 이상",
        "정격파워 450W 이상",
        "정격파워 500W 이상",
        "정격파워 550W 이상",
        "정격파워 600W 이상",
        "정격파워 650W 이상",
        "정격파워 700W 이상",
        "정격파워 750W 이상",
        "정격파워 800W 이상",
        "정격파워 850W 이상",
        "정격파워 900W 이상",
        "정격파워 1000W 이상",
      ],
      powerPorts: [
        "16핀(12VHPWR) x1",
        "8핀 x3",
        "8핀 x2",
        "8핀 x1",
        "6핀 x1 + 8핀 x1",
        "8핀 x2 + 6핀 x1",
        "6핀 x1",
        "12핀 x1",
        "없음",
        "외부AC전원",
        "GC-HPWR 전용",
      ],
      widthLength: [
        "350~359 mm",
        "340~349 mm",
        "330~339 mm",
        "320~329 mm",
        "310~319 mm",
        "300~309 mm",
        "290~299 mm",
        "280~289 mm",
        "270~279 mm",
        "260~269 mm",
        "250~259 mm",
        "240~249 mm",
        "230~239 mm",
        "220~229 mm",
        "210~219 mm",
        "200~209 mm",
        "190~199 mm",
        "180~189 mm",
        "170~179 mm",
        "160~169 mm",
        "150~159 mm",
        "140~149 mm",
        "~139 mm",
        "360~ mm",
      ],
      thickness: [
        "100~ mm",
        "80~99 mm",
        "70~79 mm",
        "60~69 mm",
        "50~59 mm",
        "45~49 mm",
        "40~44 mm",
        "35~39 mm",
        "30~34 mm",
        "~29 mm",
      ],
      additionalFeatures: [
        "백플레이트",
        "DrMOS",
        "LED 라이트",
        "LCD 모니터링",
        "Dual BIOS",
        "오버클럭 물리키",
        "수냉 장착 지원",
        "PWM 커넥터",
        "LED온오프스위치",
      ],
      ledSystem: [
        "AURA SYNC",
        "MYSTIC LIGHT",
        "RGB FUSION",
        "SPECTRA",
        "RGB LIGHTING",
        "Dynamik Light",
        "ThunderMaster",
        "XTREME TUNER",
        "Devil Zone RGB",
        "POLYCHROME",
        "VELOCITY X",
        "TuneIT",
        "EXPERTOOL2",
      ],
      warrantyPeriod: ["A/S 4년", "A/S 3년", "A/S 2년"],
    },
    ssd: {
      manufacturer: [
        "삼성전자",
        "SK하이닉스",
        "마이크론",
        "Western Digital",
        "이메이션",
        "솔리다임",
        "Seagate",
        "인텔",
        "ESSENCORE",
        "ACCLAMATOR",
        "ACOS",
        "ADATA",
        "AFOX",
        "APPLE",
        "ASUS",
        "Apacer",
        "Asgard",
        "BIOSTAR",
        "BIWIN",
        "COLORFUL",
        "COOLERTEC",
        "CORSAIR",
        "CRAFT",
        "DATARAM",
        "EAGET",
        "EKMEMORY",
        "EMTEC",
        "EVERCOOL",
        "EXASCEND",
        "FANTOM",
        "FOXCONN",
        "Fikwot",
        "GIGABYTE",
        "GLOWAY",
        "GeIL",
        "Goodram",
        "GrinMax",
        "HGST",
        "HIKSEMI",
        "HIKVISION",
        "HP",
        "ICY DOCK",
        "IPT",
        "ISG",
        "J&A",
        "JEYI",
        "KINGMAX",
        "Kim MiDi",
        "KingBank",
        "KingDian",
        "KingSpec",
        "Korlet",
        "Lexar",
        "Lite-On",
        "Longsys",
        "MAIWO",
        "MAXTEK",
        "MG",
        "MK2",
        "MSI",
        "MUSHKIN",
        "MiSD",
        "MyDigitalSSD",
        "MySSD",
        "NCTOP",
        "NEXI",
        "NOFAN",
        "Netac",
        "Nextorage",
        "OCZ SS",
        "ORICO",
        "OTAO",
        "OWC",
        "PATRIOT",
        "PHINOCOM",
        "PNY",
        "PUSKILL",
        "Plextor",
        "Reletech",
        "RiTEK",
        "SOH",
        "SSSTC",
        "STCOM",
        "Sabrent",
        "SanDisk",
        "Sandisk",
        "SilverStone",
        "Sintech",
        "Supertalent",
        "Synology",
        "TERACLE",
        "TIMETEC",
        "TOPDISK",
        "TeamGroup",
        "UNITEK",
        "Union Memory",
        "VIA",
        "Vaseky",
        "VisionTek",
        "YMTC",
        "ZOMY",
        "ZOTAC",
        "innoDisk",
        "강원전자",
        "갤럭시",
        "건평정보통신",
        "기가스톤",
        "노트옵션",
        "뉴젠테크",
        "델로라",
        "도시바",
        "동현아이디엠스토리지",
        "디오테라",
        "디지탈그리고나",
        "디직스",
        "디클",
        "라이트컴",
        "라인업시스템",
        "래안텍",
        "리더샵",
        "리버네트워크",
        "리뷰안",
        "마이크로닉스",
        "마하링크",
        "매니악",
        "명인일렉트로닉스",
        "명정보기술",
        "바른전자",
        "버바팀",
        "베이스캠프",
        "블루트레이더스",
        "비에스컴퓨터",
        "비트엠",
        "비티시스템",
        "삼성씨앤에이치",
        "상아전산",
        "서진네트웍스",
        "세마전자",
        "스카이디지탈",
        "실리콘파워",
        "쏘아이티플러스",
        "앤디코",
        "앱코",
        "에이서",
        "엑슬비젼엔터컴",
        "엘케이통상산업",
        "엠비에프",
        "엠씨케이글로벌",
        "엠지텍",
        "웨이코스",
        "위젤",
        "위즈플랫",
        "유커머스",
        "이지넷유비쿼터스",
        "인네트워크",
        "장우컴퍼니",
        "젬스톤",
        "조이쿨",
        "청연MnS",
        "컴이지",
        "컴포인트",
        "케이엘시스템",
        "케이원정보",
        "코닥",
        "퀄리티어슈어런스코리아",
        "큐닉스그룹",
        "크로셀",
        "키오시아",
        "킹스톤",
        "킹패스트",
        "타무즈",
        "탑라인에이치디",
        "태경리테일",
        "트랜센드",
        "트로이씨앤씨",
        "티테크놀로지",
        "티피원",
        "파이슨",
        "파이오니아",
        "퓨쳐솔루션",
        "프레젠샵",
        "한창코퍼레이션",
        "한캐스트",
        "확인중",
      ],
      formFactor: [
        "M.2 (2280)",
        "6.4cm(2.5형)",
        "M.2 (2230)",
        "M.2 (2242)",
        "Mini SATA(mSATA)",
        "M.2 (22110)",
        "PCIe 카드",
        "SATADOM",
        "기타",
      ],
      interface: [
        "PCIe5.0x4 (128GT/s)",
        "PCIe4.0x4 (64GT/s)",
        "PCIe3.0x4 (32GT/s)",
        "PCIe3.0x2 (16GT/s)",
        "SATA3 (6Gb/s)",
        "PCIe4.0x8 (128GT/s)",
        "PCIe3.0x16 (128GT/s)",
        "PCIe3.0x8 (64GT/s)",
        "PCIe2.0x4 (20GT/s)",
        "U.2 (PCIe3.0x4)",
        "SAS (12Gb/s)",
        "E-IDE",
        "기타",
        "U.3 (PCIe4.0x4)",
      ],
      protocol: ["NVMe 2.0", "NVMe 1.4", "NVMe 1.3", "NVMe 1.2", "NVMe"],
      capacity: [
        "4TB~3TB",
        "2TB~1.1TB",
        "1TB~600GB",
        "525GB~270GB",
        "256GB~130GB",
        "19TB~9TB",
        "8TB~5TB",
        "128GB~80GB",
        "64GB 이하",
      ],
      memoryType: [
        "TLC(토글)",
        "TLC(기타)",
        "MLC(토글)",
        "MLC(기타)",
        "QLC",
        "SLC",
        "MLC(동기식)",
      ],
      nandStructure: ["3D낸드", "2D낸드"],
      process: ["14 nm", "15 nm", "16 nm", "20 nm", "25 nm", "34 nm"],
      ramEmbedded: ["DRAM 탑재"],
      ramType: [
        "DDR4 8GB",
        "DDR4 4GB",
        "DDR4 2GB",
        "DDR4 1GB",
        "DDR4 512MB",
        "DDR4 256MB",
        "DDR3 2GB",
        "DDR3 1GB",
        "DDR3 512MB",
        "DDR3 256MB",
        "DDR3 128MB",
        "DDR2 256MB",
      ],
      controller: [
        "삼성",
        "마벨",
        "인텔",
        "실리콘모션",
        "파이슨",
        "KIOXIA",
        "도시바",
        "샌드포스",
        "JMicron",
        "ASolid",
        "Transcend",
        "Realtek",
        "Maxiotek",
        "InnoGrit",
        "기타 컨트롤러",
      ],
      sequentialRead: [
        "11,000~ MB/s",
        "9,000~10,999 MB/s",
        "6,000~8,999 MB/s",
        "4,000~5,999 MB/s",
        "2,500~3,999 MB/s",
        "1,500~2,499 MB/s",
        "1,000~1,499 MB/s",
        "550~999 MB/s",
        "450~549 MB/s",
        "350~449 MB/s",
        "250~349 MB/s",
        "~250 MB/s",
      ],
      sequentialWrite: [
        "9,000~ MB/s",
        "7,000~8,999 MB/s",
        "6,000~6,999 MB/s",
        "5,000~5,999 MB/s",
        "4,000~4,999 MB/s",
        "3,000~3,999 MB/s",
        "2,000~2,999 MB/s",
        "1,500~1,999 MB/s",
        "1,000~1,499 MB/s",
        "500~999 MB/s",
        "300~499 MB/s",
        "100~299 MB/s",
        "~99 MB/s",
      ],
      readIOPS: [
        "1,500K~",
        "1,001~1,499K",
        "501~1,000K",
        "401~500K",
        "301~400K",
        "201~300K",
        "101~200K",
        "51~100K",
        "50K 이하",
      ],
      writeIOPS: [
        "1,500K~",
        "1,001~1,499K",
        "501~1,000K",
        "401~500K",
        "301~400K",
        "201~300K",
        "101~200K",
        "51~100K",
        "~50K",
      ],
      supportFeatures: [
        "TRIM",
        "GC",
        "SLC캐싱",
        "S.M.A.R.T",
        "DEVSLP",
        "ECCHMB",
      ],
      additionalFeatures: ["AES 암호화", "RGB/LED", "전용 S/W"],
      mtbf: ["~100만 시간", "101~150만 시간", "151~200만 시간", "201만~ 시간"],
      tbw: [
        "~199 TB",
        "200~499 TB",
        "500~999 TB",
        "1,000~1,499 TB",
        "1,500~1,999 TB",
        "2,000~2,999 TB",
        "3,000~4,999 TB",
        "5,000~9,999 TB",
        "10,000~ TB",
      ],
      warranty: [
        "10년",
        "6년",
        "5년",
        "3년",
        "2년",
        "1년",
        "데이터 복구 3년",
        "데이터 복구 1년",
        "제한보증",
      ],
    },
    hdd: {
      manufacturer: [
        "Seagate",
        "Western Digital",
        "도시바",
        "CENTURY",
        "DELL",
        "Fujitsu",
        "HGST",
        "HP",
        "IBM",
        "MAIWO",
        "MARSHAL",
        "Sebap",
        "Synology",
        "TerraMaster",
        "ablelead",
        "디존아이",
        "디지털존",
        "레노버",
        "삼성전자",
        "이지넷유비쿼터스",
        "크로바하이텍",
        "한국캐드컴",
        "확인중",
      ],
      productType: [
        "HDD (PC용)",
        "HDD (노트북용)",
        "HDD (NAS용)",
        "HDD (CCTV용)",
        "HDD (기업용)",
        "SSHD (PC용)",
        "SSHD (노트북용)",
        "HDD (리퍼비시)",
        "HDD (중고)",
        "HDD 복사기",
      ],
      diskSize: ["8.9cm(3.5인치)", "6.4cm(2.5인치)", "4.6cm(1.8인치)"],
      diskCapacity: [
        "8TB",
        "4TB",
        "3TB",
        "2TB",
        "1TB",
        "24TB",
        "22TB",
        "20TB",
        "18TB",
        "16TB",
        "14TB",
        "12TB",
        "10TB",
        "6TB",
        "5TB",
        "1.5TB",
        "900GB",
        "750GB",
        "600GB",
        "500GB",
        "400GB",
        "320GB",
        "300GB",
        "250GB",
        "160GB",
        "147GB",
        "120GB",
        "80GB",
        "74GB",
        "60GB",
        "40GB 이하",
      ],
      interface: [
        "SATA3 (6Gb/s)",
        "SATA2 (3Gb/s)",
        "E-IDE",
        "SA-SCSI",
        "SA-SCSI (6Gb/s)",
        "SATA1 (1.5Gb/s)",
        "SA-SCSI (12Gb/s)",
        "SCSI",
        "ZIF타입",
        "기타",
      ],
      rotationSpeed: [
        "15,000 RPM",
        "10,000 RPM",
        "7,200 RPM",
        "5,900 RPM",
        "5,400 RPM",
        "5,640 RPM",
        "4,200 RPM",
      ],
      bufferSize: [
        "메모리 256MB",
        "메모리 128MB",
        "메모리 64MB",
        "메모리 32MB",
        "메모리 16MB",
        "메모리 512MB",
        "메모리 8MB",
        "메모리 2MB 이하",
      ],
      transferSpeed: [
        "160MB/s 이하",
        "161~190MB/s",
        "191~220MB/s",
        "221~250MB/s",
        "251MB/s 이상",
      ],
      recordingMethod: ["CMR(PMR)", "SMR(PMR)", "확인요망(PMR)", "TGMR"],
      diskCount: [
        "플래터 1장",
        "플래터 2장",
        "플래터 3장",
        "플래터 4장",
        "플래터 5장 이상",
      ],
      additionalFeatures: [
        "헬륨충전",
        "RV센서",
        "DSA",
        "S.M.A.R.T 지원",
        "ISE",
        "SED",
        "저전력",
      ],
      mtbf: [
        "60만 시간",
        "80만 시간",
        "100만 시간",
        "120만 시간",
        "140만 시간",
        "150만 시간",
        "200만 시간",
        "250만 시간",
      ],
      warranty: [
        "1년",
        "2년",
        "3년",
        "5년",
        "데이터 복구 5년",
        "데이터 복구 3년",
        "데이터 복구 2년",
      ],
    },
    case: {
      manufacturer: [
        "앱코",
        "darkFlash",
        "마이크로닉스",
        "아이구주",
        "COX",
        "DAVEN",
        "잘만",
        "1stPlayer",
        "NZXT",
        "HYTE",
        "리안리",
        "Fractal Design",
        "써멀테이크",
        "be quiet",
        "ASUS",
        "JONSBO",
        "180도",
        "1st HANYANG",
        "2MONS",
        "3RSYS",
        "ADATA",
        "ADT Link",
        "AEROCOOL",
        "AKASA",
        "ALPHACOOL",
        "ALSEYE",
        "AMAQUEST",
        "ANIX",
        "AONE",
        "APNX",
        "Antec",
        "BIGS",
        "BITFENIX",
        "BRAVOTEC",
        "CABLEMATE",
        "CHENBRO",
        "COLORFUL",
        "COOLMAI",
        "CORSAIR",
        "COUGAR",
        "DAMONCOM",
        "DEEPCOOL",
        "EDDY",
        "EVERCOOL",
        "EVGA",
        "G.SKILL",
        "GAMDIAS",
        "GDEVIL",
        "GEEEK",
        "GEO메트릭퓨처",
        "GIGABYTE",
        "GSI",
        "HP",
        "HYDRA",
        "IN WIN",
        "JDM코리아",
        "JONSPLUS",
        "KRAFT KOREA",
        "LINKUP",
        "MK2",
        "MONTECH",
        "MSI",
        "Motsoul",
        "NCTOP",
        "NEWRUN",
        "NEWZEN",
        "OCPC",
        "ORBIS",
        "PB이노베이션",
        "PCCOOLER",
        "PNC PARTNER",
        "Phanteks",
        "RAIDMAX",
        "RAIJINTEK",
        "REX COOL",
        "RMS",
        "Razer",
        "SAMA",
        "SNK테크",
        "SSUPD",
        "STCOM",
        "Segotep",
        "SilverStone",
        "SonicGearLab",
        "Supermicro",
        "TYAN",
        "Thermal Grizzly",
        "XIGMATEK",
        "XOCOM",
        "XTIA",
        "iStarUSA",
        "갤럭시",
        "거인전자",
        "건평정보통신",
        "고랩",
        "다산코퍼레이션",
        "다얼유",
        "다오테크",
        "대양케이스",
        "디지탈그리고나",
        "디지털하우스",
        "라벤타",
        "라이트컴",
        "라인업시스템",
        "리버네트워크",
        "매니악",
        "맥스엘리트",
        "메이커스잼",
        "모드컴",
        "몬스타",
        "바이퍼테크",
        "발키리",
        "비콘즈",
        "샤칸",
        "선경씨앤씨",
        "세솔",
        "세컨드찬스",
        "셀텍",
        "슈미드",
        "스카이디지탈",
        "시소닉",
        "신한아이앤씨",
        "씨넥스존",
        "아이에스엔티",
        "아이폴코리아",
        "어스큐레이션",
        "에너맥스",
        "엔비케이텍",
        "엠스톤글로벌",
        "엠제이테크놀로지",
        "영재컴퓨터",
        "오존컴퍼니",
        "유한하이테크",
        "이메이크",
        "이아이인터내셔널",
        "이엠텍",
        "이지넷유비쿼터스",
        "인네트워크",
        "주연테크",
        "주피터씨앤씨",
        "컴이지",
        "컴퓨터광장",
        "케이엘시스템",
        "쿨러마스터",
        "큐닉스그룹",
        "투렉스",
        "투민시스템",
        "포게임",
        "프라임디렉트",
        "피닉스CNS",
        "피에스플러스",
        "확인중",
      ],
      productType: [
        "PC케이스(ATX)",
        "PC케이스(M-ATX)",
        "미니ITX",
        "HTPC 케이스",
        "튜닝 케이스",
        "PC케이스(RTX)",
        "랙마운트",
        "액세서리",
      ],
      caseSize: [
        "빅타워",
        "미들타워",
        "미니타워",
        "미니타워(LP)",
        "미니ITX(리틀밸리)",
        "데스크탑",
        "슬림(일반)",
        "슬림(LP)",
        "마이크로타워",
        "랙마운트(1U)",
        "랙마운트(2U)",
        "랙마운트(3U)",
        "랙마운트(4U) 이상",
      ],
      powerSupply: [
        "표준-ATX",
        "M-ATX(SFX)",
        "TFX",
        "DC to DC",
        "FLEX",
        "리던던트",
      ],
      boardSupport: [
        "ATX",
        "M-ATX",
        "ITX",
        "E-ATX",
        "M-ITX",
        "ATX (후면커넥터)",
        "M-ATX (후면커넥터)",
        "F-ATX",
        "SSI-CEB",
        "SSI-EEB",
        "M-DTX",
      ],
      bay13cm: ["4개 이상", "3개 이하", "1개"],
      bay89cm: ["8개 이상", "7개", "6개", "5개", "4개", "3개", "2개", "1개"],
      storageMount: ["최대 4개 이상", "최대 3개", "최대 2개", "최대 1개"],
      verticalPCI: ["기본형", "슬롯변경형"],
      coolingFans: [
        "총 9개",
        "총 8개",
        "총 7개",
        "총 6개",
        "총 5개",
        "총 4개",
        "총 3개",
        "총 2개",
        "총 1개",
        "총 미지원",
      ],
      ledFans: ["1개", "2개", "3개", "4개", "5개", "6개", "7개", "8개 이상"],
      frontPanel: ["메쉬", "강화유리", "일반(솔리드)"],
      sideOpening: ["스윙도어", "버튼"],
      side: ["통풍구", "쿨링팬", "아크릴", "강화유리", "강철"],
      rear: [
        "141mm LED 이상",
        "140mm LED",
        "120mm LED",
        "140mm 이상",
        "120mm",
        "92mm",
        "80mm",
        "60mm",
      ],
      front: [
        "200mm LED",
        "185mm LED",
        "180mm LED",
        "160mm LED",
        "140mm LED",
        "120mm LED",
        "200mm",
        "180mm",
        "140mm",
        "120mm",
        "92mm",
        "80mm",
        "60mm",
        "40mm 이하",
      ],
      top: [
        "141mm LED 이상",
        "140mm LED",
        "120mm LED",
        "140mm 이상",
        "120mm",
        "92mm",
        "80mm",
      ],
      dustFilter: ["전체", "부분"],
      vgaMountLength: [
        "400~ mm",
        "350~399 mm",
        "300~349 mm",
        "250~299 mm",
        "200~249 mm",
        "~199 mm",
      ],
      cpuCoolerHeight: [
        "200mm 이상",
        "190~199mm",
        "180~189mm",
        "170~179mm",
        "160~169mm",
        "150~159mm",
        "140~149mm",
        "130~139mm",
        "120~129mm",
        "119mm 이하",
      ],
      liquidCoolerSupport: [
        "최대 3열 지원",
        "최대 2열 지원",
        "최대 1열 지원",
        "최대 4열 지원",
      ],
      radiatorTop: [
        "최대 560mm, 480mm",
        "최대 480mm, 420mm",
        "최대 480mm, 280mm",
        "최대 480mm",
        "최대 420mm, 360mm",
        "최대 420mm",
        "최대 360mm, 280mm",
        "최대 360mm",
        "최대 280mm, 240mm",
        "최대 280mm",
        "최대 240mm, 140mm",
        "최대 240mm",
        "최대 140mm, 120mm",
        "최대 140mm",
        "최대 120mm",
      ],
      radiatorFront: [
        "최대 600mm, 560mm",
        "최대 560mm, 480mm",
        "최대 480mm, 420mm",
        "최대 480mm, 280mm",
        "최대 480mm",
        "최대 420mm, 360mm",
        "최대 420mm",
        "최대 360mm, 280mm",
        "최대 360mm",
        "최대 280mm, 240mm",
        "최대 280mm",
        "최대 240mm, 140mm",
        "최대 240mm",
        "최대 140mm, 120mm",
        "최대 140mm",
        "최대 120mm",
      ],
      radiatorRear: [
        "최대 600mm, 560mm",
        "최대 420mm, 360mm",
        "최대 360mm, 280mm",
        "최대 280mm, 240mm",
        "최대 240mm, 140mm",
        "최대 240mm",
        "최대 140mm, 120mm",
        "최대 140mm",
        "최대 120mm",
      ],
      additionalFeatures: [
        "LED 라이트",
        "방음패드 내장",
        "상태표시 창",
        "HDD 도킹",
        "PC방 전용",
        "수랭쿨링홀",
        "채굴용(마이닝)",
        "켄싱턴 락",
        "상단 패널 탈착",
        "그래픽카드 지지대",
      ],
      ledTuning: ["내부 LED 바", "외부 LED", "측면 LED 투과"],
      controllerSupport: [
        "팬 컨트롤",
        "RGB 컨트롤",
        "리모컨",
        "외부LED 컨트롤",
      ],
      caseColor: [
        "블랙 계열",
        "화이트 계열",
        "레드 계열",
        "실버 계열",
        "옐로우 계열",
        "블루 계열",
        "핑크 계열",
        "오렌지 계열",
        "그린 계열",
        "골드 계열",
        "퍼플 계열",
      ],
    },
    power: {
      manufacturer: [
        "시소닉",
        "앱코",
        "MSI",
        "마이크로닉스",
        "맥스엘리트",
        "잘만",
        "darkFlash",
        "아이구주",
        "쿨러마스터",
        "포게임",
        "AONE",
        "ASUS",
        "리안리",
        "be quiet",
        "+0asis",
        "+PLUS",
        "180도",
        "2MONS",
        "3RSYS",
        "ABB코리아",
        "ABSL",
        "ADATA",
        "ANDYSON",
        "ANIX",
        "ANP",
        "APC",
        "ATEN",
        "ATUM",
        "Ablerex",
        "AcBEL",
        "Antec",
        "BABEL",
        "BM POWER",
        "Bestone",
        "CJ ENM",
        "COLORFUL",
        "CORSAIR",
        "COUGAR",
        "COX",
        "CSB",
        "DEEPCOOL",
        "EATON",
        "EVGA",
        "EZMAX",
        "Emerson",
        "Enhance",
        "FSP",
        "Fractal Design",
        "GIGABYTE",
        "GIGAZONE",
        "GMC",
        "GSI",
        "GeIL",
        "GreatWall",
        "HALO",
        "HOPELY",
        "ICE COOL",
        "ICE-CUBE",
        "JHVISION",
        "KRAFT KOREA",
        "KSTAR",
        "LG전자",
        "MIK",
        "NCTOP",
        "NEWZEN",
        "NOFAN",
        "NZXT",
        "ORBIS",
        "PCM",
        "PNC PARTNER",
        "POWEREX",
        "Phanteks",
        "PowerFul",
        "REX COOL",
        "SAMA",
        "SNK테크",
        "STARSWAY",
        "SURE STAR",
        "Segotep",
        "SilverStone",
        "SuperFlower",
        "TAGER",
        "VOLT",
        "WEED",
        "XOCOM",
        "ares",
        "topower",
        "개풍전자",
        "뉴젠테크",
        "델타",
        "라이트컴",
        "롯데알미늄",
        "르그랑코리아",
        "마이존",
        "모드컴",
        "몬스타",
        "블루트레이더스",
        "비콘즈",
        "빅스컴",
        "삼성전자",
        "샤칸",
        "성주컴텍",
        "세븐팀",
        "세솔",
        "세컨드찬스",
        "셀텍",
        "슈미드",
        "스카이디지탈",
        "스파클텍",
        "써멀테이크",
        "썬루트",
        "썬즈",
        "알피티랜드",
        "에너맥스",
        "에너지옵티머스",
        "에스제이디지텍",
        "에즈윈",
        "아이피씨",
        "엔비케이텍",
        "오존컴퍼니",
        "이도디스플레이",
        "이엠텍",
        "제이씨현",
        "중앙시스템",
        "케이씨커머스",
        "케이씨컴",
        "티앤에스인터내셔널",
        "파워가드",
        "퍼스트큐브씨앤씨",
        "피닉스CNS",
        "픽스콤",
        "한국이스트",
        "현대파워",
        "확인중",
      ],
      productType: [
        "ATX 파워",
        "M-ATX(SFX) 파워",
        "TFX 파워",
        "서버용 파워",
        "Flex-ATX 파워",
        "UPS",
        "리던던트",
        "DC to DC",
        "전용 액세서리",
      ],
      ratedOutput: [
        "2000W 이상",
        "1600W~1999W",
        "1300W~1599W",
        "1000W~1299W",
        "900W~999W",
        "800W~899W",
        "700W~799W",
        "600W~699W",
        "500W~599W",
        "450W~499W",
        "400W~449W",
        "350W~399W",
        "300W~349W",
        "250W~299W",
        "250W 미만",
      ],
      certification80Plus: [
        "80 PLUS 티타늄",
        "80 PLUS 플래티넘",
        "80 PLUS 골드",
        "80 PLUS 실버",
        "80 PLUS 브론즈",
        "80 PLUS 스탠다드",
      ],
      certificationETA: [
        "TITANIUM",
        "PLATINUM",
        "GOLD",
        "SILVER",
        "BRONZE",
        "A++",
        "A+",
        "A",
      ],
      certificationLAMBDA: [
        "A++",
        "A+",
        "A",
        "STANDARD++",
        "STANDARD+",
        "STANDARD",
      ],
      outputType12V: ["+12V 싱글레일", "+12V 다중레일", "+12V 싱글/다중"],
      pfcCircuit: ["액티브PFC"],
      coolingFanSize: [
        "140mm 팬 이상",
        "135mm 팬",
        "130mm 팬",
        "120mm 팬",
        "92mm 팬",
        "90mm 팬",
        "80mm 팬",
        "60mm 팬",
        "60mm 팬 미만",
      ],
      warrantyPeriod: [
        "무상 8년 이상",
        "무상 7년",
        "무상 6년",
        "무상 5년",
        "무상 3년",
        "무상 2년",
        "무상 1년",
        "무상 1년 미만",
      ],
      cableConnection: ["풀모듈러", "세미모듈러", "케이블일체형"],
      mainPower: ["24핀(20+4)", "24핀", "24핀 2개"],
      auxiliaryPower: [
        "8핀(4+4) 1개",
        "8핀(4+4) 2개",
        "8핀(4+4) 3개",
        "8핀(4+4) 4개",
        "8+4핀 1개",
        "8+4+4핀 1개",
        "8+4+4핀 2개",
        "8+4+4+4핀 1개",
        "8(4+4)+4핀 1개",
        "4핀 1개",
        "8핀 1개",
        "8+8핀 1개",
      ],
      pcie16pin: [
        "12VHPWR 1개",
        "12VHPWR 2개",
        "12VHPWR 3개 이상",
        "12V2x6 1개",
        "12V2x6 2개",
        "12V2x6 3개 이상",
      ],
      additionalFeatures: [
        "플랫케이블",
        "대기전력 1W 미만",
        "LED 라이트",
        "프리볼트",
        "팬리스모드",
        "자동 팬 조절",
        "수동 팬 조절",
        "디지털제어",
      ],
      ledSystem: [
        "AURA SYNC",
        "MYSTIC LIGHT",
        "RGB FUSION",
        "POLYCHROME",
        "RAZER CHROMA",
        "TT RGB PLUS",
      ],
    },
  });
  const getters = ref({
    cpu: {
      manufacturer: "제조사",
      intelCpuTypes: "인텔 CPU종류",
      amdCpuTypes: "AMD CPU종류",
      socketTypes: "소켓 구분",
      manufacturingProcesses: "제조 공정",
      coreCounts: "코어 수",
      threadCounts: "스레드 수",
      baseClocks: "기본 클럭",
      boostClocks: "최대 클럭",
      l3Caches: "L3 캐시",
      tdps: "TDP",
      pcieVersions: "PCIe 버전",
      maxPcieLanes: "최대 PCIe 레인수",
      maxMemorySizes: "최대 메모리 크기",
      memoryTypes: "메모리 규격",
      memorySpeeds: "메모리 클럭",
      integratedGraphics: "내장그래픽",
      gpuModels: "GPU 모델명",
      supportedTechnologies: "기술 지원",
      codeNames: "코드 네임",
      packageTypes: "패키지 형태",
      coolerTypes: "쿨러",
    },
    coolerTuning: {
      manufacturer: "제조사",
      productType: "제품 종류",
      coolingType: "냉각 방식",
      warranty: "A/S기간",
      intelSocket: "인텔 소켓",
      amdSocket: "AMD 소켓",
      height: "높이",
      radiator: "라디에이터",
      fanSize: "팬 크기",
      bearingType: "베어링",
      maxFanSpeed: "최대 팬속도",
      maxAirFlow: "최대 풍량",
      minFanNoise: "최저 팬소음",
      maxFanNoise: "최대 팬소음",
      ledSystem: "LED시스템",
      additionalFeatures: "부가기능",
      thermalType: "써멀유형",
    },
    motherboard: {
      manufacturer: "제조사",
      productType: "제품 분류",
      cpuSocket: "CPU 소켓",
      chipset: "세부 칩셋",
      formFactor: "폼팩터",
      powerPhase: "전원부",
      vcoreOutput: "Vcore출력합계",
      memoryType: "메모리 종류",
      memorySpeed: "메모리 속도",
      memorySlots: "메모리 슬롯",
      memoryCapacity: "메모리 용량",
      vgaConnection: "VGA 연결",
      pcieVersion: "PCIe버전",
      sata: "SATA3",
      m2: "M.2",
      graphicOutput: "그래픽 출력",
      rearPorts: "후면단자",
      rearUsb3_20Gbps: "USB3.x 20Gbps",
      rearUsb2_0: "USB2.0",
      wiredLanChipset: "유선랜 칩셋",
      wirelessLanType: "무선랜 종류",
      audioChipset: "오디오 칩셋",
      ledSystem: "LED 시스템",
    },
    memory: {
      manufacturer: "제조사",
      deviceType: "사용 장치",
      productTypes: "제품 분류",
      memoryCapacity: "메모리 용량",
      operatingClock: "동작클럭(대역폭)",
      ramTiming: "램타이밍",
      operatingVoltage: "동작전압",
      numberOfModules: "램개수",
      features: "부가기능",
      heatSink: "히트싱크",
      heatSinkColor: "방열판 색상",
      ledColor: "LED색상",
      ledSystem: "LED 시스템",
    },
    gpu: {
      manufacturer: "제조사",
      chipsetManufacturer: "칩셋 제조사",
      productSeries: "제품 시리즈",
      gpuManufacturingProcess: "GPU 제조 공정",
      nvidiaChipset: "NVIDIA 칩셋",
      amdChipset: "AMD 칩셋",
      intelChipset: "인텔 칩셋",
      baseClock: "베이스클럭",
      boostClock: "부스트클럭",
      streamProcessors: "스트림 프로세서",
      interface: "인터페이스",
      memoryType: "메모리 종류",
      memoryCapacity: "메모리 용량",
      memoryBus: "메모리 버스",
      outputPort: "출력단자",
      dvi: "DVI",
      hdmi: "HDMI",
      displayPort: "DisplayPort",
      monitorSupport: "모니터 지원",
      supportFeatures: "지원기능",
      powerConsumption: "사용전력",
      recommendedPower: "권장 파워용량",
      powerPorts: "전원 포트",
      widthLength: "가로(길이)",
      thickness: "두께",
      additionalFeatures: "부가기능",
      ledSystem: "LED 시스템",
      warrantyPeriod: "제품보증기간",
    },
    ssd: {
      manufacturer: "제조사",
      formFactor: "폼팩터",
      interface: "인터페이스",
      protocol: "프로토콜",
      capacity: "용량",
      memoryType: "메모리 타입",
      nandStructure: "낸드 구조",
      process: "공정",
      ramEmbedded: "RAM 탑재",
      ramType: "RAM 타입",
      controller: "컨트롤러",
      sequentialRead: "순차읽기",
      sequentialWrite: "순차쓰기",
      readIOPS: "읽기IOPS",
      writeIOPS: "쓰기IOPS",
      supportFeatures: "지원기능",
      additionalFeatures: "부가기능",
      mtbf: "MTBF",
      tbw: "TBW",
      warranty: "A/S기간",
    },
    hdd: {
      manufacturer: "제조사",
      productType: "제품 분류",
      diskSize: "디스크 크기",
      diskCapacity: "디스크 용량",
      interface: "인터페이스",
      rotationSpeed: "회전수",
      bufferSize: "버퍼 용량",
      transferSpeed: "전송 속도",
      recordingMethod: "기록방식",
      diskCount: "디스크 수",
      additionalFeatures: "부가기능",
      mtbf: "사용보증",
      warranty: "A/S 정보",
    },
    case: {
      manufacturer: "제조사",
      productType: "제품 분류",
      caseSize: "케이스 크기",
      powerSupply: "지원파워규격",
      boardSupport: "지원보드규격",
      bay13cm: "13.3cm베이",
      bay89cm: "8.9cm베이",
      storageMount: "저장장치 장착",
      verticalPCI: "수직 PCI형태",
      coolingFans: "쿨링팬",
      ledFans: "LED팬",
      frontPanel: "전면 패널 타입",
      sideOpening: "측면 개폐 방식",
      side: "측면",
      rear: "후면",
      front: "전면",
      top: "상단",
      dustFilter: "먼지필터",
      vgaMountLength: "VGA 장착 길이",
      cpuCoolerHeight: "CPU쿨러 장착높이",
      liquidCoolerSupport: "수랭쿨러 규격",
      radiatorTop: "라디에이터(상단)",
      radiatorFront: "라디에이터(전면)",
      radiatorRear: "라디에이터(후면)",
      additionalFeatures: "부가기능",
      ledTuning: "LED 튜닝",
      controllerSupport: "컨트롤러 지원",
      caseColor: "케이스 색상 계열",
    },
    power: {
      manufacturer: "제조사",
      productType: "제품 분류",
      ratedOutput: "정격출력",
      certification80Plus: "80PLUS인증",
      certificationETA: "ETA인증",
      certificationLAMBDA: "LAMBDA인증",
      outputType12V: "+12V 출력방식",
      pfcCircuit: "PFC회로",
      coolingFanSize: "쿨링팬 크기",
      warrantyPeriod: "A/S 보증기간",
      cableConnection: "케이블연결",
      mainPower: "메인전원",
      auxiliaryPower: "보조전원",
      pcie16pin: "PCIe 16핀(12+4)",
      additionalFeatures: "부가기능",
      ledSystem: "LED 시스템",
    },
  });
  return {
    filterList,
    getters,
  };
});
